# 1. What is a Python library? Why do we use Python libraries?

In Python, libraries are collections of pre-written, reusable code modules that provide functionality for various tasks. These modules contain functions, classes, and variables that you can import and use directly in your Python programs.

Here are few reasons why we use python libraries:

* **Reusability:** Python libraries allow us to to reuse the code that has already been written. 
* **Increased productivity:** Python libraries provide ready to use solutions for a wide range of tasks, numerical computing to machine learning.
* **Perfomance Optimization:**   Many Python libraries are implemented in low level languages like C or C++, which can significantly improve performance for computationally intensive tasks.
* **Community and Support:** Many popular libaries have robust communities offering support through forums, documentation and tutorials. This allows you to seek assistance and learn from other's experiences when encountering challanges.
 #### Examples of Python Libraries:
 * **Numpy:** Used in numerical computing and array manipulation.
 * **Pandas:** Used for data analysis and manipulation
 * **Matplotlib:** Used for Data visualization
 * **Sciket learn:** Used in machine learning

# 2. What is the difference between Numpy array and List?

Numpy arrays and Python lists are both data strutures used to store data, but they have several key differences:

* **Data Types**: In Python lists, elements can be of any data type. In contrast numpy arrays are homogenous, meaning all the elements in the array must have the same data type.
* **Memory Effciency:** Numpy arays are more memory effcient than python lists. Thee effciency is achieved because numpy arrays are implemented as contiguous blocks of memory, whereas Python lists are arrays of pointers to objects dcattered thoughout memory. Additionaly, numpy arrays store data in a more compact format, which reduces memory overhead.
* **Performance:** Numpy arrays offer better performance for numerical computations compared to Python lists. Numpy provides optimized implementations of mathematical operations that operate on entire arrays at once (vectorized operations), whereas in Python, you would typically need to use loops to perform the same operations on list elements. This vectorization leads to faster execution times for numerical computations with Numpy arrays.
* **Functionality:** Numpy arrays offer a wide range of built in functions and methods for performing mathematical operations, array manipulation, linear algebra, random number generation, and more. Python lists, while versatile, have fewer built-in functions and are not optimized for numerical computations.
* **Indexing and Slicing:** Both Numpy arrays and Python lists support indexing and slicing to access elements or sublists. However, Numpy arrays offer more advanced indexing techniques, such as boolean indexing and fancy indexing, which allow for more flexible and efficient data manipulation.
* **Mutablity:** Numpy arrays and Python lists are mutable, meaning their elements can be modified after creation. However, Numpy arrays have fixed sizes, so you cannot directly append or remove elements from an existing array like you can with Python lists. Instead, you typically create new arrays with the desired elements.

# 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np

In [15]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr.shape

(3, 4)

In [13]:
arr.size

12

In [10]:
arr.ndim

2

# 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [17]:
arr1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]                    # create the array

firstrow = arr1[0]                                          # accessing the first element using indexing

print(firstrow)

[1, 2, 3, 4]


# 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

To access the element at the third row and fourth column from the given numpy array, we can use array indexing with  square brackets. In python, indexing starts from 0, so the third row and fourth column corrospond to index 2 and 3 respectively. here is  how can we do it.

In [19]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ele = arr2[2,3]
print("element at the third row and fourth column is " , ele)

element at the third row and fourth column is  12


# 6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [23]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])


odd_elements = arr[:, 1::2]        

print(odd_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

We can generate a random 3x3 matrix with values betweeen 0 and 1 using numpy's  **np.random.rand()** function. This function generates random values from a uniform distribution over the interval [0, 1). 

In [26]:
arr4 = np.random.rand(3,3)
arr4

array([[0.13132984, 0.29627998, 0.14358287],
       [0.7728163 , 0.89501993, 0.49087173],
       [0.37032416, 0.15722242, 0.62485554]])

# 8. Describe the difference between np.random.rand and np.random.randn?



In [27]:
# To illustrate the differences, consider the followinfg code


# Generate random numbers from uniform distribution
uniform_samples = np.random.rand(3, 4)

# Generate random numbers from standard normal distribution
normal_samples = np.random.randn(3, 4)

print(uniform_samples)  # Values will be between 0 (inclusive) and 1 (exclusive)
print(normal_samples)  # Values will be centered around 0 and have decreasing probability as they move away


[[0.97748422 0.31236782 0.48561549 0.20996515]
 [0.80560595 0.87424482 0.88175895 0.93322954]
 [0.24151741 0.61398119 0.67042948 0.35044043]]
[[-0.1982299  -0.24461481 -0.47035617 -0.31587968]
 [-1.13843065  1.17409239  0.86563452  0.02229783]
 [-0.9951195  -1.33178292 -0.88224848 -0.20329824]]


np.random.rand is for uniform distribution within [0, 1).
                                                   
np.random.randn is for the standard normal distribution with a mean of 0 and a standard deviation of 1.

# 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [29]:
arr5 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

expanded = np.expand_dims(arr5 , axis = 0)

print(expanded)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


# 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [31]:
# We can transpose the given array using the np.transpose function or by accessing the T attribute of the numpy array

arr6 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

transposed_arr = np.transpose(arr6)

print("Original array:")
print(arr6)
print("\nTransposed array:")
print(transposed_arr)




Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# 11. Consider the following matrix:

Matrix A [
[1, 2, 3, 4] 
[5, 6, 7, 8],
[9, 10, 11, 12]
]

Matrix B [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


# Perform the following operation using Python:
* **Index wise multiplication**
* **Matrix multiplication**
* **Add both matices**
* **Subtract matrix B from A**
* **Divide Matrix B by A**


In [39]:
A = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

B = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

index_mul = A*B
matrix_mul = A @ B.T
add = A+B
sub = A - B
div = B / A

print("Index wise matrix multiplication of matrices A and B is :" )
print(index_mul)


print("Matrix multiplication of matrices A and B is:" )
print(matrix_mul)


print("Sum is:")
print(add)


print("difference between A and B is")
print( sub)


print("B divide by A is :")
print( div)

Index wise matrix multiplication of matrices A and B is :
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication of matrices A and B is:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Sum is:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
difference between A and B is
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
B divide by A is :
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 12.  Which function in Numpy can be used to swap the byte order of an array?

In Numpy, you can use the `numpy.ndarray.byteswap()` function to swap the byte order of an array. This function swaps the byte order (endianness) of the elements in the array in-place. Here is how we can do it.



In [40]:
arr = np.array([1, 256, 65536], dtype=np.int32)


arr.byteswap(True)                                   # Swap the byte order of the array

print("Original array:", arr)


Original array: [16777216    65536      256]


# 13.  What is the significance of the np.linalg.inv function?

The `np.linalg.inv()` function in numpy is used to compute the inverse of a square matrix.Here is how we do it

In [42]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])

# Compute the inverse of the matrix A
A_inv = np.linalg.inv(A)

print("Original matrix A:")
print(A)
print("Inverse of matrix A:")
print(A_inv)


Original matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
Inverse of matrix A:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


# 14. What does the np.reshape function do, and how is it used?

`np.reshape` function reshapes an array into a new shape without changing its data. It returns a new array with the specified shape.



In [49]:
# Example

arr10 = np.arange(12)
reshaped_arr = np.reshape(arr10, (3, 4))

print("Original array:")
print(arr10)
print("Reshaped array:")
print(reshaped_arr)


Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 15. What is broadcasting in numpy?


The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operations. This process involves certain rules that allow the smaller array to be ‘broadcast’ across the larger one, ensuring that they have compatible shapes for these operations.

In [50]:
# Example

a = np.array([5, 7, 3, 1]) 
b = np.array([90, 50, 0, 30]) 
  
# array are compatible because of same Dimension 
c = a * b 
print(c) 

[450 350   0  30]
